/**
 * NOTE: This class is auto generated by the io.swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.BasicResponse;
import io.swagger.model.ProblemInfo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-07-07T02:38:17.975Z[GMT]")
@Api(value = "problems", description = "the problems API")
public interface ProblemsApi {

    @ApiOperation(value = "增加题目", nickname = "addProblems", notes = "增加一道题目到题库 ", response = BasicResponse.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "项目被创建", response = BasicResponse.class),
        @ApiResponse(code = 401, message = "参数错误") })
    @RequestMapping(value = "/problems",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<BasicResponse> addProblems(@ApiParam(value = ""  )  @Valid @RequestBody ProblemInfo body);

}
