/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.QuerryInfo;
import io.swagger.model.QuerryResult;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-07-15T03:10:29.413Z[GMT]")
@Api(value = "queryCollection", description = "the queryCollection API")
public interface QueryCollectionApi {

    @ApiOperation(value = "查询题目集合信息", nickname = "queryCollection", notes = "按条件查询集合，与查询题目一模一样，不过是去集合里面找而已 ", response = QuerryResult.class, tags = {})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "返回查询到的项目列表", response = QuerryResult.class),
            @ApiResponse(code = 401, message = "参数格式错误")})
    @RequestMapping(value = "/queryCollection",
            produces = {"application/json"},
            consumes = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<QuerryResult> queryCollection(@ApiParam(value = "") @Valid @RequestBody QuerryInfo body);

}
