/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.BasicResponse;
import io.swagger.model.UserInfo;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-07-15T03:10:29.413Z[GMT]")
@Api(value = "userInfo", description = "the userInfo API")
public interface UserInfoApi {

    @ApiOperation(value = "增加用户信息", nickname = "userInfoPost", notes = "", response = BasicResponse.class, tags = {})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = BasicResponse.class),
            @ApiResponse(code = 401, message = "参数错误")})
    @RequestMapping(value = "/userInfo",
            produces = {"application/json"},
            consumes = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<io.swagger.pojo.dto.BasicResponse> userInfoPost(@ApiParam(value = "") @Valid @RequestBody UserInfo body);

}
