/**
 * 题库外部接口
 * 题库系统供其他应用调用的接口
 *
 * OpenAPI spec version: 1.1.0
 * Contact: czfshine@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 排序方式，type 有desc 和asce 两种，next是下一级的排序项
 */
export interface OrderInfo { 
    sorttype: OrderInfo.SorttypeEnum;
    field: string;
    next?: OrderInfo;
}
export namespace OrderInfo {
    export type SorttypeEnum = 'desc' | 'asce';
    export const SorttypeEnum = {
        Desc: 'desc' as SorttypeEnum,
        Asce: 'asce' as SorttypeEnum
    };
}