/**
 * 题库外部接口
 * 题库系统供其他应用调用的接口
 *
 * OpenAPI spec version: 1.1.0
 * Contact: czfshine@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 待获取的状态查询信息列表，下面三个是and的关系
 */
export interface ProblemIdList { 
    /**
     * 题库对应的id，从管理平台获取
     */
    poolId: string;
    /**
     * 验证用户权限的OAuth令牌，从管理平台申请，暂时无用
     */
    token: string;
    /**
     * 问题id列表
     */
    ids?: Array<string>;
    /**
     * 用户id列表
     */
    unionids?: Array<string>;
    /**
     * 状态列表
     */
    status?: Array<string>;
}