/**
 * 题库外部接口
 * 题库系统供其他应用调用的接口
 *
 * OpenAPI spec version: 1.1.0
 * Contact: czfshine@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { Expression } from './expression';
import { OrderInfo } from './orderInfo';
import { Pagination } from './pagination';


export interface QuerryInfo { 
    /**
     * 题库对应的id，从管理平台获取
     */
    poolId: string;
    /**
     * 验证用户权限的OAuth令牌，从管理平台申请，暂时无用
     */
    token: string;
    querry: Expression;
    /**
     * 是否打乱顺序输出
     */
    random?: boolean;
    /**
     * 是否递归获取所有信息 为false的话，result就只是一个id列表数组 为true的话，result是具体的信息对象，在可能有大量结果的时候慎用
     */
    deep?: boolean;
    ordering?: OrderInfo;
    pagination?: Pagination;
}